/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *str_t;

struct input {
	str_t path;
	int a;
	int b;
};
typedef struct input input;

#define PARTB_PROG 0x12345678
#define PARTB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define partb 1
extern  char ** partb_1(input *, CLIENT *);
extern  char ** partb_1_svc(input *, struct svc_req *);
extern int partb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define partb 1
extern  char ** partb_1();
extern  char ** partb_1_svc();
extern int partb_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str_t (XDR *, str_t*);
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_str_t ();
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
