/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "part_b.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	 if (!xdr_str_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}
